apiVersion: v1
kind: Service
metadata:
  name: APP_NAME_PLACEHOLDER-service
  namespace: APP_NAME_PLACEHOLDER
spec:
  selector:
    app: APP_NAME_PLACEHOLDER
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: NODE_PORT_PLACEHOLDER  # Wird durch Kustomize ersetzt
  type: NodePort
