apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-simple-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bug-sult/opentofu.git
    targetRevision: HEAD
    path: kubernetes/demo-simple-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-simple-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
