apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  namespace: keycloak
type: Opaque
stringData:
  username: admin
  password: admin123
---
apiVersion: k8s.keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
---
apiVersion: k8s.keycloak.org/v1alpha1
kind: KeycloakRealmImport
metadata:
  name: example-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: example
    enabled: true
    users:
      - username: testuser
        enabled: true
        emailVerified: true
        firstName: Test
        lastName: User
        email: testuser@example.com
        credentials:
          - type: password
            value: test123
            temporary: false
