apiVersion: v1
kind: Service
metadata:
  name: example-backend-service
  namespace: example-app
spec:
  selector:
    app: example-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 80
      nodePort: 30081
  type: NodePort
