apiVersion: v1
kind: Service
metadata:
  name: testing-testapp-service
  namespace: testing-testapp
spec:
  selector:
    app: testing-testapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090
  type: NodePort
