applications:
%{ for app in applications ~}
  - name: ${app.name}
    project: default
    source:
      repoURL: ${repo_url}
      targetRevision: HEAD
      path: ${app.path}
    destination:
      server: https://kubernetes.default.svc
      namespace: ${app.namespace}
    syncPolicy:
      automated: {}
      syncOptions:
        - CreateNamespace=true
%{ endfor ~}
