apiVersion: v1
kind: Service
metadata:
  name: gruppe-5-tester-app2
  namespace: gruppe-5-tester-app2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gruppe-5-tester-app2
