apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
      - name: movie-backend
        image: movie-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "movieapp"
        - name: DB_PASSWORD
          value: "movieapp123"
        - name: DB_NAME
          value: "moviedb"
        - name: DB_PORT
          value: "5432"
        - name: KEYCLOAK_URL
          value: "http://keycloak-service.keycloak.svc.cluster.local:8080"
        - name: FRONTEND_URL
          value: "http://localhost:30083"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: movie-backend-service
  namespace: movie-app
spec:
  selector:
    app: movie-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30084
  type: NodePort
