apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
      - name: movie-frontend
        image: movie-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:30084"
        - name: REACT_APP_KEYCLOAK_URL
          value: "http://localhost:30082"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: movie-frontend-service
  namespace: movie-app
spec:
  selector:
    app: movie-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30083
  type: NodePort
