apiVersion: v1
kind: Service
metadata:
  name: test-template-app-service
  namespace: test-template-app
spec:
  selector:
    app: test-template-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30087  # Eindeutiger Port für Test-App
  type: NodePort
