apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.k8s.keycloak.org
spec:
  group: k8s.keycloak.org
  versions:
  - name: v2alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instances:
                type: integer
                minimum: 1
              image:
                type: string
              hostname:
                type: string
              tlsSecret:
                type: string
              db:
                type: object
                properties:
                  vendor:
                    type: string
                  host:
                    type: string
                  port:
                    type: integer
                  database:
                    type: string
                  usernameSecret:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                  passwordSecret:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
              http:
                type: object
                properties:
                  tlsSecret:
                    type: string
              additionalOptions:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    message:
                      type: string
  scope: Namespaced
  names:
    plural: keycloaks
    singular: keycloak
    kind: Keycloak
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmimports.k8s.keycloak.org
spec:
  group: k8s.keycloak.org
  versions:
  - name: v2alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              keycloakCRName:
                type: string
              realm:
                type: object
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    message:
                      type: string
  scope: Namespaced
  names:
    plural: keycloakrealmimports
    singular: keycloakrealmimport
    kind: KeycloakRealmImport
