apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: h2
  hostname:
    hostname: keycloak.local
    strict: false
    strictHttps: false
  http:
    enabled: true
    port: 8080
  ingress:
    enabled: false
  features:
    enabled:
      - infinispan
  proxy:
    enabled: true
    reencrypt: false
  additionalOptions:
    - name: proxy
      value: edge
    - name: log-level
      value: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  namespace: keycloak
type: Opaque
stringData:
  username: admin
  password: admin123
