apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - simple-keycloak.yaml
  - realm-import-configmap.yaml

configMapGenerator:
  - name: keycloak-realm-config
    files:
      - gitops-realm.json
    options:
      disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: keycloak-realm-config
    targets:
      - select:
          kind: Deployment
          name: keycloak
        fieldPaths:
          - spec.template.spec.volumes.[name=realm-config].configMap.name
