apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: example-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: example-realm
    enabled: true
    displayName: Example Application Realm
    accessTokenLifespan: 300
    ssoSessionIdleTimeout: 1800
    ssoSessionMaxLifespan: 36000
    offlineSessionIdleTimeout: 2592000
    clients:
      - clientId: example-app
        name: Example Application
        enabled: true
        protocol: openid-connect
        publicClient: true
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
        redirectUris:
          - "http://*:30080/*"
          - "http://localhost:30080/*"
          - "http://keycloak.local:30080/*"
        webOrigins:
          - "http://*:30080"
          - "http://localhost:30080"
          - "http://keycloak.local:30080"
        attributes:
          post.logout.redirect.uris: "+"
          pkce.code.challenge.method: "S256"
    users:
      - username: testuser
        enabled: true
        firstName: Test
        lastName: User
        email: test@example.com
        credentials:
          - type: password
            value: test123
            temporary: false
        realmRoles:
          - user
    roles:
      realm:
        - name: user
          description: Regular user role
          composite: false
          clientRole: false
