apiVersion: v1
kind: Service
metadata:
  name: gruppe-5-tester-app1
  namespace: gruppe-5-tester-app1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30091
  selector:
    app: gruppe-5-tester-app1
