apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gruppe-5-tester
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bug-sult/opentofu.git
    targetRevision: HEAD
    path: kubernetes/gruppe-5-tester/child-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
