apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-appl-frontend
  namespace: test-appl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-appl-frontend
  template:
    metadata:
      labels:
        app: test-appl-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
      volumes:
      - name: html-content
        configMap:
          name: test-appl-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-appl-content
  namespace: test-appl
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="de">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TEST-APPL - GitOps Demo</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 0;
                padding: 20px;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
            }
            .container {
                background: white;
                padding: 3rem;
                border-radius: 15px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                text-align: center;
                max-width: 800px;
                width: 100%;
            }
            h1 {
                color: #333;
                margin-bottom: 1rem;
                font-size: 2.5rem;
            }
            .subtitle {
                color: #666;
                margin-bottom: 2rem;
                font-size: 1.2rem;
            }
            .status {
                background: #e8f5e8;
                color: #2e7d32;
                padding: 1rem;
                border-radius: 8px;
                margin: 1rem 0;
                font-weight: bold;
            }
            .info-section {
                background: #f8f9fa;
                padding: 2rem;
                border-radius: 10px;
                margin: 1rem 0;
                text-align: left;
            }
            .deployment-info {
                background: #e3f2fd;
                padding: 1.5rem;
                border-radius: 8px;
                margin: 1rem 0;
            }
            .feature-list {
                list-style: none;
                padding: 0;
            }
            .feature-list li {
                padding: 0.5rem 0;
                border-bottom: 1px solid #eee;
            }
            .feature-list li:before {
                content: "✅ ";
                margin-right: 0.5rem;
            }
            .workflow-step {
                background: #fff3e0;
                padding: 1rem;
                margin: 0.5rem 0;
                border-left: 4px solid #ff9800;
                border-radius: 4px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 TEST-APPL</h1>
            <p class="subtitle">Automatisierte GitOps Demo-Anwendung</p>
            
            <div class="status">
                ✅ Anwendung erfolgreich über GitOps deployed!
            </div>

            <div class="deployment-info">
                <h3>📋 Deployment-Informationen</h3>
                <ul class="feature-list">
                    <li><strong>Anwendungsname:</strong> TEST-APPL</li>
                    <li><strong>Namespace:</strong> test-appl</li>
                    <li><strong>Deployment:</strong> Kubernetes mit ArgoCD</li>
                    <li><strong>CI/CD:</strong> GitHub Actions</li>
                    <li><strong>GitOps:</strong> Automatisches Sync</li>
                    <li><strong>Service Type:</strong> NodePort (Port 30088)</li>
                </ul>
            </div>

            <div class="info-section">
                <h3>🔄 GitOps Workflow</h3>
                <div class="workflow-step">
                    <strong>1. Code Push:</strong> Änderungen werden zu GitHub Repository gepusht
                </div>
                <div class="workflow-step">
                    <strong>2. GitHub Actions:</strong> Automatische Validierung und Deployment
                </div>
                <div class="workflow-step">
                    <strong>3. ArgoCD Sync:</strong> Automatische Synchronisation mit Kubernetes
                </div>
                <div class="workflow-step">
                    <strong>4. Live Update:</strong> Anwendung wird automatisch aktualisiert
                </div>
            </div>

            <div class="info-section">
                <h3>📊 Anwendungsdetails</h3>
                <p><strong>Version:</strong> 1.0.0</p>
                <p><strong>Build Zeit:</strong> <span id="buildTime"></span></p>
                <p><strong>Status:</strong> <span style="color: green;">Running</span></p>
                <p><strong>Container:</strong> nginx:alpine</p>
                <p><strong>Replicas:</strong> 1</p>
            </div>

            <div class="info-section">
                <h3>🛠️ Technische Details</h3>
                <p><strong>Kubernetes Namespace:</strong> test-appl</p>
                <p><strong>Service Name:</strong> test-appl-service</p>
                <p><strong>Deployment Name:</strong> test-appl-frontend</p>
                <p><strong>ConfigMap:</strong> test-appl-content</p>
                <p><strong>ArgoCD Application:</strong> test-appl</p>
            </div>
        </div>

        <script>
            // Zeige aktuelle Zeit als Build-Zeit
            document.getElementById('buildTime').textContent = new Date().toLocaleString('de-DE');
            
            // Einfache Animation für den Status
            setInterval(function() {
                const status = document.querySelector('.status');
                status.style.opacity = status.style.opacity === '0.7' ? '1' : '0.7';
            }, 2000);
        </script>
    </body>
    </html>
