apiVersion: v1
kind: Service
metadata:
  name: demo-simple-app-service
  namespace: demo-simple-app
spec:
  selector:
    app: demo-simple-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30089
  type: NodePort
