apiVersion: v1
kind: Service
metadata:
  name: test-app-2-service
  namespace: test-app-2
spec:
  selector:
    app: test-app-2-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30089
  type: NodePort
